import fitz
import pdfplumber
import pandas as pd
import numpy as np
from pathlib import Path
from datetime import datetime
import re
# =============================================
# VAULTGUARD — PDF Forensics Engine
# Analyzes PDF bank statements for tampering
# Two layers:
# 1. PDF structure analysis (cybersecurity)
# 2. Transaction data analysis (ML features)
# =============================================
def analyze_pdf_metadata(pdf_path: str) ->dict:
    findings = []
    risk_points = 0
    
    doc = fitz.open(pdf_path)

    metadata = doc.metadata
    
    print(f"=== PDF METADATA ===")
    print(f"Author:   {metadata.get('author', 'Unknown')}")
    print(f"Creator:  {metadata.get('creator', 'Unknown')}")
    print(f"Producer: {metadata.get('producer', 'Unknown')}")
    print(f"Created:  {metadata.get('creationDate', 'Unknown')}")
    print(f"Modified: {metadata.get('modDate', 'Unknown')}")
    print()

    # ── CHECK 1: Was PDF modified after creation? ──
    # Real bank statements are generated once and never edited
    # If creation date ≠ modification date = someone edited it
    creation_date = metadata.get('creationDate', '')
    mod_date = metadata.get('modDate', '')
    if creation_date and mod_date:
        if creation_date != mod_date:
            findings.append(
                "pdf was modified after original creation"
            )
        risk_points +=25
     # ── CHECK 2: Was it created by suspicious software? ──
    # Real bank statements are generated by core banking systems
    # If PDF editor software is detected = someone tampered it
    creator = metadata.get('creator', '').lower()
    producer = metadata.get('producer', '').lower()
    suspicious_tools = [
        'adobe acrobat', 'smallpdf', 'ilovepdf',
        'pdf editor', 'nitro', 'foxit'
    ]
    for tool in suspicious_tools:
        if tool in creator or tool in producer:
            findings.append(
                f"PDF was edited using: {tool}"
            )
            risk_points += 30
            break
    # ── CHECK 3: Multiple edit layers? ──
    # PDFs can have annotation layers on top of base content
    # Too many annotations = multiple editing sessions
    page_count   = doc.page_count
    total_annots = 0

    for page_num in range(page_count):
        page   = doc[page_num]  # Get specific page
        annots = list(page.annots())  # Get annotations on page
        total_annots += len(annots)

    if total_annots > 5:
        findings.append(
            f"PDF has {total_annots} annotations — signs of editing"
        )
        risk_points += 20

    # Always close the document to free memory
    doc.close()

    # Return results as dictionary
    return {
        "metadata_risk_points": risk_points,
        "metadata_findings":    findings,
        "creator":              metadata.get('creator', 'Unknown'),
        "was_modified":         creation_date != mod_date
    }
def analyze_pdf_fonts(pdf_path: str) -> dict:
    """
    Layer 1B — Analyze fonts for inconsistencies.
    
    Why fonts matter:
    Real bank statements use 1-2 fonts consistently
    throughout the entire document — because one
    software generated the whole thing.
    
    Tampered statements mix fonts because:
    → Fraudster copies text from different PDFs
    → Each source PDF had different fonts
    → Result: Helvetica on page 1, Arial on page 2
    → This inconsistency is invisible to human eye
    → But our code catches it!
    """
    findings = []
    risk_points = 0
    all_fonts = set()
    doc = fitz.open(pdf_path)
    all_fonts = set()
    for page_num in range(doc.page_count):
        page = doc[page_num]
        fonts = page.get_fonts()
        for font in fonts:
            font_name = font[3]
            all_fonts.add(font_name)
    print(f"=== FONT ANALYSIS ===")
    print(f"Total unique fonts found: {len(all_fonts)}")
    print(f"Font names: {all_fonts}")
    print()        
    # ── CHECK 1: Too many different fonts? ──
    # Legitimate bank statement: 1-2 fonts max
    # Tampered statement: 4+ fonts from different sources
    if len(all_fonts) > 4:
        findings.append(
            f"Too many fonts: {len(all_fonts)} detected "
            f"— possible copy-paste from different sources"
        )
        risk_points += 25

    # ── CHECK 2: Suspicious font names? ──
    # Some fonts only appear in specific editors
    # Their presence signals the PDF was edited
    suspicious_fonts = [
        'courier',      # Old typewriter font — unusual in modern statements
        'wingdings',    # Symbol font — no reason to be in statements
        'comic sans',   # Never used in professional documents
    ]

    for font in all_fonts:
        font_lower = font.lower()
        for suspicious in suspicious_fonts:
            if suspicious in font_lower:
                findings.append(
                    f"Suspicious font detected: {font}"
                )
                risk_points += 15

    doc.close()

    return {
        "font_risk_points": risk_points,
        "font_findings":    findings,
        "fonts_detected":   list(all_fonts),
        "font_count":       len(all_fonts)
    }
def extract_transactions(pdf_path: str) -> pd.DataFrame:
    """
    Layer 2 — Extract transaction data from PDF.
    
    This function reads the actual text content
    of the PDF and finds transaction lines.
    
    A transaction line looks like:
    "01/01/2024  SALARY CREDIT  50000.00  49342.00"
     date        description    amount    balance
    
    We use Regular Expressions (regex) to find
    all numbers in each line and extract them.
    """
    transactions = [] 
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue
            lines = text.split('\n')
            for line in lines:
                numbers = re.findall(r'\d+\.\d+|\d+', line)
                if len(numbers) >= 2:
                    try:
                        # Last number in line = balance
                        # Second to last = transaction amount
                        # This pattern holds for most bank statements
                        amount  = float(numbers[-2])
                        balance = float(numbers[-1])

                        # Filter out header rows and tiny numbers
                        # Real transactions have amount > 10
                        if amount > 10 and balance > 0:

                            # Determine if credit or debit
                            # by looking for keywords in the line
                            line_lower = line.lower()
                            is_credit  = any(
                                word in line_lower
                                for word in [
                                    'credit', 'salary',
                                    'deposit', 'received', 'refund'
                                ]
                            )
                            # any() returns True if ANY word found
                            # "salary credit neft 50000" → True
                            # "upi payment 2000" → False

                            transactions.append({
                                "raw_line":  line.strip(),
                                "amount":    amount,
                                "balance":   balance,
                                "is_credit": is_credit
                            })

                    except (ValueError, IndexError):
                        # ValueError: float("abc") fails
                        # IndexError: numbers[-2] fails if < 2 items
                        # continue skips this line and tries next
                        continue

    # Handle case where no transactions found
    if len(transactions) == 0:
        print("⚠️  No transactions extracted from PDF")
        return pd.DataFrame()  # Return empty DataFrame

    df = pd.DataFrame(transactions)
    print(f"✅ Extracted {len(df)} transactions from PDF")
    return df
def calculate_features(transactions_df: pd.DataFrame) -> dict:
    """
    Calculate ML features from extracted transactions.
    
    Takes the raw transactions extracted from PDF
    and converts them into the 10 features our
    ML model expects.
    
    This connects the PDF forensics layer to the
    ML prediction layer — the bridge between them.
    """

    # Handle empty DataFrame — no transactions found
    if transactions_df.empty:
        print("⚠️  No transactions — returning default features")
        # Return neutral default values
        # Model will give medium risk score
        return {
            "round_number_ratio":      0.5,
            "salary_is_round":         0,
            "salary_variance":         0,
            "min_balance":             0,
            "avg_balance":             0,
            "balance_variance":        0,
            "transaction_count":       0,
            "avg_debit":               0,
            "large_transaction_ratio": 0,
            "credit_debit_ratio":      1.0
        }

    df = transactions_df

    # Separate credits and debits into two groups
    # is_credit=True  → money coming IN  (salary, deposits)
    # is_credit=False → money going OUT  (spending, withdrawals)
    credits = df[df["is_credit"] == True]["amount"]
    debits  = df[df["is_credit"] == False]["amount"]

    # ── Feature 1: Round Number Ratio ──
    # What % of spending transactions are round numbers?
    if len(debits) > 0:
        round_ratio = float((debits % 100 == 0).mean())
    else:
        round_ratio = 0.0

    # ── Feature 2 & 3: Salary Analysis ──
    # Large credits (>10000) are likely salary
    # Small credits could be refunds/cashbacks
    salary = credits[credits > 10000]

    if len(salary) > 0:
        # Is first salary credit a round number?
        salary_is_round = int(salary.iloc[0] % 1000 == 0)

        # How much does salary vary across months?
        # std() needs at least 2 values to calculate
        if len(salary) > 1:
            salary_variance = float(salary.std())
        else:
            salary_variance = 0.0
            # 0 variance when only 1 salary found
            # Could mean statement period is < 1 month
    else:
        salary_is_round = 0
        salary_variance = 0.0

    # ── Features 4, 5, 6: Balance Features ──
    min_balance      = float(df["balance"].min())
    avg_balance      = float(df["balance"].mean())
    balance_variance = float(df["balance"].std())

    # ── Feature 7: Transaction Count ──
    # Total number of transactions in statement
    transaction_count = len(df)

    # ── Feature 8: Average Debit ──
    # Average amount spent per transaction
    if len(debits) > 0:
        avg_debit = float(debits.mean())
    else:
        avg_debit = 0.0

    # ── Feature 9: Large Transaction Ratio ──
    # What % of transactions are above ₹10,000?
    if len(debits) > 0:
        large_ratio = float((debits > 10000).mean())
    else:
        large_ratio = 0.0

    # ── Feature 10: Credit Debit Ratio ──
    # Total money in / Total money out
    # Legitimate: close to 1.0 (spending matches income)
    # Fraud: higher ratio (credits inflated)
    total_credit = float(credits.sum())
    total_debit  = float(debits.sum())

    if total_debit > 0:
        credit_debit_ratio = total_credit / total_debit
    else:
        credit_debit_ratio = 1.0
        # Default 1.0 if no debits found

    # Print summary for debugging
    print(f"=== EXTRACTED FEATURES ===")
    print(f"Round number ratio:  {round_ratio:.2f}")
    print(f"Salary is round:     {salary_is_round}")
    print(f"Salary variance:     {salary_variance:.2f}")
    print(f"Min balance:         ₹{min_balance:,.0f}")
    print(f"Avg balance:         ₹{avg_balance:,.0f}")
    print(f"Transaction count:   {transaction_count}")
    print(f"Avg debit:           ₹{avg_debit:,.0f}")
    print()

    # Return all features as dictionary
    # Keys match EXACTLY what ML model was trained on
    return {
        "round_number_ratio":      round_ratio,
        "salary_is_round":         salary_is_round,
        "salary_variance":         salary_variance,
        "min_balance":             min_balance,
        "avg_balance":             avg_balance,
        "balance_variance":        balance_variance,
        "transaction_count":       transaction_count,
        "avg_debit":               avg_debit,
        "large_transaction_ratio": large_ratio,
        "credit_debit_ratio":      credit_debit_ratio
    }
def analyze_full_statement(pdf_path: str) -> dict:
    """
    Master function — runs ALL forensics checks
    and returns one complete analysis report.
    
    This is the only function called from outside.
    It coordinates all other functions and combines
    their results into one final report.
    
    Think of it as the conductor of an orchestra —
    it doesn't play instruments itself, it coordinates
    all musicians (functions) together.
    """

    print(f"\n{'='*50}")
    print(f"ANALYZING: {pdf_path}")
    print(f"{'='*50}\n")

    # Step 1 — Run metadata forensics
    # Checks: creation date, modification date,
    #         editing software, annotation layers
    metadata_analysis = analyze_pdf_metadata(pdf_path)

    # Step 2 — Run font forensics
    # Checks: number of fonts, suspicious font names
    font_analysis = analyze_pdf_fonts(pdf_path)

    # Step 3 — Extract transactions from PDF
    # Reads text, finds transaction lines,
    # returns DataFrame of transactions
    transactions = extract_transactions(pdf_path)

    # Step 4 — Calculate ML features
    # Converts transactions into 10 feature numbers
    # that our ML model understands
    features = calculate_features(transactions)

    # Step 5 — Combine forensics risk scores
    # metadata risk + font risk = total forensics risk
    total_forensics_risk = (
        metadata_analysis["metadata_risk_points"] +
        font_analysis["font_risk_points"]
    )

    # Step 6 — Combine all findings into one list
    # + operator joins two lists together
    all_findings = (
        metadata_analysis["metadata_findings"] +
        font_analysis["font_findings"]
    )

    # Return everything as one big dictionary
    return {
        "features":           features,
        "forensics_risk":     total_forensics_risk,
        "forensics_findings": all_findings,
        "metadata":           metadata_analysis,
        "fonts":              font_analysis,
        "transaction_count":  len(transactions)
    }
